[tool.poetry]
name = "the-stolen-crown-rpg"
version = "0.1.0"
description = ""
authors = ["justinmeister"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pygame-ce = "^2.5.1"
PyTMX = "^3.32"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
